version: '3'
services:
  development:
    container_name: MyDevelopment
    image: docker.pkg.github.com/betancourtca/vscode.devcontainers/skunkworks:0.0.2
    volumes:
    - workspace:/workspace
    - ./shared:/root/shared
    - ../.aws:/root/.aws
    - /var/run/docker.sock:/var/run/docker.sock

    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
  # covid-registry-db:
  #   image: mysql:5.7.22
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: "covidregistry"
  #     MYSQL_ROOT_PASSWORD: "example"
volumes: 
  workspace: