version: '3'
services:
  dev_container:
    container_name: SpaceJanitor
    build: .
    volumes:
    - /workspace:/workspace
    - ~/downloads:/root/downloads
    - ~/data:/root/data
    - ~/.ssh:/root/.ssh
    - ~/.aws:/root/.aws
    - ~/.kube:/root/.kube
    - ~/.vscode:/root/.vscode
    - ~/.npmrc:/root/.npmrc
    - /var/run/docker.sock:/var/run/docker.sock
    # - ~/.gitconfig:/root/.gitconfig
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: mysql:8
    expose:
      - "3306"
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mysqldata:/var/lib/mysql 
volumes:
  mysqldata: